spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: contexto_pool
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000
    url: ${DATABASE_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  cloud:
    aws:
      region:
        static: us-east-1
      s3:
        endpoint: ${MINIO_ENDPOINT}
        path-style-access-enabled: true
      credentials:
        access-key: ${MINIO_ACCESS_KEY}
        secret-key: ${MINIO_SECRET_KEY}



langchain4j:
  vertexai:
    project-id: ${GCP_PROJECT_ID}
    location: ${GCP_LOCATION}
    chat-model:
      model-name: gemini-2.5-flash
    embedding-model:
      model-name: text-embedding-004

    vector-store:
      pgvector:
        host: localhost
        port: 5432
        database: contexto_db
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        table-name: vector_store
        dimension: 768

application:
  storage:
    bucket-name: ${MINIO_BUCKET_NAME}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-hours: 8